### ISSUE TITLE
role should be able to create user, database and grants

### ISSUE THREAD

**Issue by p-thurner** [blunix/role-mariadb#8]
The role should be able to create the "static" aspects of the database, which can then be used by the "deployment" part of an application in their config files - create:
- user
- database
- grants

similar to this:
```
mariadb_users:
  - name: frank
    state: present
    password: secretpass
mariadb_databases:
  - wordpress: present
mariadb_grants:
  - grant: ALL
    state: present
    database: 'wordpress.*'
    user: frank
    host: '172.20.0.%'
```
